In [1]:
import numpy as np

In [8]:
x = np.array([1, 2, 3, 4])
print(x)
A = np.array([[1,2],[3,4],[5,6]])
print(type(A))
print(type(x))

[1 2 3 4]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [12]:
print(A.shape)
print(x.shape)
print(len(x))

(3, 2)
(4,)
4


In [17]:
A_T = A.T

In [22]:
B = np.array([[2, 5], [7, 4], [4, 3]])
C = A + B
D = A + 1

In [29]:
E = np.array([[2], [4]])
F = np.dot(A, E)
F = A.dot(E)
print(F.shape)

(3, 1)


In [31]:
I = np.eye(3)
IA = I.dot(A)
print(IA)

[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [35]:
M = np.array([[1,2],[3,4]])
det_M = np.linalg.det(M)
print(det_M)
#N = np.array([[1,2],[3,4],[5,6]])
#det_N = np.linalg.det(N)
#print(det_N)

-2.0000000000000004


In [38]:
N = np.array([[3, 0, 2], [2, 0, -2], [0, 1, 1]])
N_inv = np.linalg.inv(N)
print(N)
print(N_inv)
I = N_inv.dot(N)
print(I)

[[ 3  0  2]
 [ 2  0 -2]
 [ 0  1  1]]
[[ 0.2  0.2  0. ]
 [-0.2  0.3  1. ]
 [ 0.2 -0.3 -0. ]]
[[ 1.00000000e+00  0.00000000e+00 -1.11022302e-16]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]
