In [1]:
import numpy as np

In [8]:
a = np.array([1,2,3], dtype='int16')

In [4]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [5]:
print(b.ndim)

2


In [6]:
print(a.shape)

(3,)


In [12]:
print(a.dtype)
print(a.itemsize)
print(a.nbytes)

int16
2
6


In [13]:
c = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

In [17]:
c[1,5]

13

In [18]:
c[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [20]:
c[:,2]

array([ 3, 10])

In [21]:
c[0,1:6:2]

array([2, 4, 6])

In [22]:
c[1,5] = 20
c[:,2]=[1,2]

In [23]:
d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [27]:
d[0,1,1]

4

In [28]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [29]:
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [30]:
np.full((2,3),99)

array([[99, 99, 99],
       [99, 99, 99]])

In [31]:
np.random.rand(4,2)

array([[0.25244335, 0.91865656],
       [0.6326399 , 0.45880702],
       [0.95120063, 0.32105569],
       [0.56852951, 0.15960332]])

In [32]:
np.random.randint(-8,8,size=(3,30))

array([[ 0,  6,  7, -2, -1, -7, -6,  5,  6,  4, -5,  7, -1, -8, -2, -6,
        -6,  0, -8,  7, -3, -1,  2,  0, -4,  3,  5, -2, -6, -4],
       [-6,  5,  4,  7,  6, -8, -5, -3, -4,  6,  6,  7,  3,  7, -8,  6,
        -6,  1, -5, -3, -2, -7, -7,  1,  2,  7, -7, -4, -6, -8],
       [ 3,  4, -6,  5, -3,  2, -7,  1, -4,  2,  4,  0,  2, -5,  6, -6,
         7,  2, -8,  0, -6,  3,  7,  7, -2,  6, -5, -6, -1, -2]])

In [33]:
np.identity(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [37]:
np.repeat([[1,2,3]],3,axis=0)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [41]:
output = np.ones((5,5))
output[1:4,1:4]=np.zeros((3,3))
output[2,2]=9
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [43]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)
print(b)

[1 2 3]
[100   2   3]


In [44]:
e = np.ones((2,3))
f = np.full((3,2),2)
np.matmul(e,f)

array([[6., 6.],
       [6., 6.]])

In [46]:
np.linalg.det(np.matmul(e,f))

0.0

In [48]:
stats = np.array([[1,2,3],[4,5,6]])

In [49]:
np.min(stats)

1

In [50]:
np.max(stats,axis=1)

array([3, 6])

In [51]:
np.sum(stats,axis=0)

array([5, 7, 9])

In [53]:
np.array([[1,2,3],[4,5,6]]).reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])